name: Build

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: powershell
    env:
      TEST_USERNAME: docker
      TEST_PASSWORD: tmpBCContainerPWD1!
      CONTAINER_NAME: tmp
      APP_NAME: seminar-management.app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate AL Code
        uses: mdal-lang/mdal-action@v1
        with:
          model-file: src/seminar-management.mdal
      - uses: actions/upload-artifact@v2
        with:
          name: generated-code
          path: src-gen
      - name: Set up BC Container
        run: |
          Install-Module BcContainerHelper -Force
          Get-Command -Module BcContainerHelper | Out-Null
          New-BcContainer `
            -artifactUrl (Get-BCArtifactUrl -type OnPrem -version 16 -country w1 -select Latest) `
            -containerName $env:CONTAINER_NAME `
            -accept_eula `
            -accept_outdated `
            -auth NavUserPassword `
            -credential (New-Object PSCredential $env:TEST_USERNAME, (ConvertTo-SecureString $env:TEST_PASSWORD -AsPlainText -Force)) `
            -additionalParameters @('--volume ' + '"' + (Join-Path $pwd ":c:\share") + '"')
      - name: Build App
        run: |
          Compile-AppInBCContainer `
            -containerName $env:CONTAINER_NAME `
            -credential (New-Object PSCredential $env:TEST_USERNAME, (ConvertTo-SecureString $env:TEST_PASSWORD -AsPlainText -Force)) `
            -appProjectFolder $pwd `
            -appOutputFolder $pwd `
            -appName $env:APP_NAME
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.APP_NAME }}
